name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=21.3.1
  - ydata-profiling
  - requests=2.24.0
  - Jupyter
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip:
      - mlflow==2.11.3
      - wandb==0.16.4
