name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - hydra-core=1.1.0
  - seaborn=0.11.1
  - scikit-learn=0.24.1
  - matplotlib=3.8.3
  - pandas=1.2.3
  - Jupiter
  #- jupyterlab=4.0.9
  - pip=23.3.1
  - pip:
      - mlflow==2.11.3
      - wandb==0.16.4