name: trtain_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - hydra-core=1.1.0
  - matplotlib=3.8.3
  - pandas=1.2.3
  - pip=23.3.1
  - scikit-learn==0.24.2
  - pip:
      - mlflow==2.11.3
      - wandb==0.16.4
